variables:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: edrodefeld/parakeet
      auto_tag: true
      cache_from: type=registry,ref=edrodefeld/parakeet:buildcache
      cache_to: type=registry,ref=edrodefeld/parakeet:buildcache,mode=max
      <<: *docker_creds
    when:
      - event: [push, manual]
        branch: main

  deploy:
    image: bitnami/kubectl
    commands:
      - kubectl rollout restart deployment/parakeet -n galaxy
    when:
      - event: [push, manual]
        branch: main
